[workspace]

members = [
    "app",
    "screen_cap",
    "utils",
]

[profile.release]
lto = true

[profile.release-with-debug]
inherits = "release"
incremental = false
lto = true
debug = true

[profile.release-no-lto]
inherits = "release"
incremental = false
lto = false